### ISSUE TITLE
Unable download the datasets 

### ISSUE THREAD

**Issue by PHChenGit** [OSUPCVLab/PCVLabDrone2021#1]
Hi

This work is so amazing, so I try to reproduce on my own uav.
However, I cannot download the datasets you provided,
because the system requires OSU accounts.
Do you provide the others way to download the datasets?

Thanks.

**Comment by JianliWei1995** [comment]
Hi,

Happy to hear that. May I know which datasets you cannot download or can you request any access on your end? If so I can approve your request immediately.

Thanks,

**Comment by PHChenGit** [comment]
Hi @JianliWei1995 

I followed the UAV Geolocalization module Readme.md instrutions to download datasets.
Here is the Readme.md screenshot to show the link position in the Readme.md.
![Screenshot from 2024-02-27 09-35-41](https://github.com/OSUPCVLab/PCVLabDrone2021/assets/16322329/2254a06b-67fe-41ba-9e76-826b25e4e904)

If you allow, I hope I can download the all images and videos.
It is because of that I want to followed the methods metioned in the paper at the beginning to make sure I am doing right. Then, I will try to make my own datasets.

Thank you.

**Comment by JianliWei1995** [comment]
Sorry about the inconvenience. Can you please provide your email so I can share the folder with you then you can download the datasets with the link?

Thanks,

**Comment by PHChenGit** [comment]
Thanks.
This is really great and so kind of you for all the follow up answers.
My email is t112598072@ntut.org.tw  .
Thank you again. It is really helpful.

**Comment by JianliWei1995** [comment]
Link was shared to your email. You can also try opening this link from incognito window https://buckeyemailosu-my.sharepoint.com/:f:/g/personal/wei_909_buckeyemail_osu_edu/EsKgV2SqsXxGv9abhpAyWJ8BNDzGAPKsaUTD8jot28q47w?e=GaUAQb

**Comment by PHChenGit** [comment]
It is really helpful. Thanks you again.
I have already download the all datasets.
